### PR TITLE
Remove dependency on .NET SDK installs for IL Tools

### LINKED ISSUE #2298: Remove dependency on .NET SDK installs for IL Tools
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) 5.0.100-alpha1-015914
* Windows version: (`winver`) 1909 (10.0.18363)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: No
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?  No

 **Problem description:** Build failure when suitable .NET SDK is not installed

**Repro steps:**
1. New machine with Win10 1909 (hence .NET 4.8).
2. Setup machine per [WPF developer guide](https://github.com/dotnet/wpf/blob/master/Documentation/developer-guide.md).
3. Fork/clone master branch of dotnet/wpf.
4. Obtain fix for #2297 
5. build 
 
 **Actual behavior:** 
 D:\repos\wpf\eng\WpfArcadeSdk\tools\InjectModuleInitializer.targets(372,5): error MSB4044: The "ILDasmTask" task was not given a value for the required parameter "ILDAsm". [D:\repos\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\PresentationCore.csproj]

 **Expected behavior:** No failure
 
This failure goes away after installing .NET 4.6.1 SDK, which makes a version of ildasm.exe visible to
PresentationCore.csproj.  Note that ilasm.exe is already visible (at C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ILAsm.exe) before installing a .NET SDK

### PR DESCRIPTION
**Pull request by rladuca**
Fixes #2298

Use a set of matched, private IL tools in order to inject a module constructor into `PresentationCore`.  These are copied binaries from a .NET Framework 4.7.2 installation and SDK.

Also fixing some issues with utilizing `ILAsm` outside of the installed Framework directory and some bugs that went unnoticed in our injection targets.

# Pending
- [x] IL comparison between `PresentationCore` from this change and current .NET 5.0 `PresentationCore`.

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
You have to undo @SamBent's documentation update.

**Comment by vatsan-madhavan** [comment]
Instead of inventing new targets for ILAsm/ILDasm, you can reuse those supplied by `Microsoft.NET.Sdk.IL.targets` that comes as part of `Microsot.NET.Sdk.il` package, and override `ILAsmToolPath` ? 

As long as the commandline usage have remained largely compatible between .NET Framework and .NET Core versions of ILAsm/ILDasm, I suspect that this would be doable.

**Comment by rladuca** [comment]
> Instead of inventing new targets for ILAsm/ILDasm, you can reuse those supplied by `Microsoft.NET.Sdk.IL.targets` that comes as part of `Microsot.NET.Sdk.il` package, and override `ILAsmToolPath` ?
> 
> As long as the commandline usage have remained largely compatible between .NET Framework and .NET Core versions of ILAsm/ILDasm, I suspect that this would be doable.

I don't think [those targets ](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/.nuget/Microsoft.NET.Sdk.IL/targets/Microsoft.NET.Sdk.IL.targets) are fully featured.  While you can override the IL(D)AsmDir properties to choose non-package based tools, it seems there is only a target to decompile resources and a target to compile an IL file.  They also don't accept some switches that we use.  Generally, they seem created for a specific purpose and not for general use unless I am missing something.

**Comment by vatsan-madhavan** [comment]
>Generally, they seem created for a specific purpose and not for general use 

 😞

**Comment by rladuca** [comment]
IL comparison seems fine, no major differences there between corresponding release DLLs.

File: eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs [hunk 1]
```diff
@@ -1,80 +1,80 @@
...
+        {
+            try
+            {
+                var moduleConstructorIL = File.ReadAllText(ModuleConstructorIL);
+                var msCorLibAssemblySectionIL = File.ReadAllText(MsCorLibAssemblySectionIL);
+                var sourceIL = File.ReadAllText(ILFile);
+
+                using (var outputIL = new StreamWriter(File.Open(ILFile, FileMode.Truncate)))
+                {
+                    if (Regex.Match(sourceIL, @"\.assembly extern mscorlib", RegexOptions.Singleline) == Match.Empty)
```
Comment (SamBent) [inline eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs]: If sourceIL already contains mscorlib reference, shouldn't you fail now?   If I understand what you've told me, that situation will produce IL where the module initializer precedes the mscorlib reference, which leads ilasm to fail silently (by not including the module init).  So catching this now when we can complain loudly seems good.

Comment (rladuca) [reply eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs]: Yeah, when we first did this we wanted to keep it general.  However, given the failure mode is silent, we should be as loud as possible when things seem incorrect.

Comment (rladuca) [reply eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs]: I decided just to make it work by replacing the mscorlib reference when we find it with the combined set of what we mean to inject (assembly reference included).  If we do not find it, we inject both from scratch at the beginning.

File: eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs [hunk 2]
```diff
@@ -41,31 +41,33 @@ public override bool Execute()
...
-                    else
+                    if (Regex.Match(sourceIL, @"\.class private auto ansi '\<Module\>'.+?\.method private hidebysig specialname rtspecialname static void \.cctor \(\) cil managed ", RegexOptions.Singleline) != Match.Empty)
                     {
                         Log.LogError("Cannot insert a module initializer into an assembly that already contains one.");
                         return false;
                     }
 
-                    outputIL.WriteLine(sourceIL);
+                    // Attempt to replace an existing mscorlib reference with the reference + module initializer.
+                    string modifiedIL = Regex.Replace(sourceIL, @"\.assembly extern mscorlib.+};", ilToInject, RegexOptions.Singleline);
```
Comment (SamBent) [inline eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs]: You're now looking for a multi-line pattern, from ".assembly extern mscorlib" to the matching "};" several lines later.
So SingleLine isn't right.

Comment (SamBent) [reply eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs]: I take that back.  "Singleline" does not mean what I thought it meant.  Never start a land war in Asia.

Comment (rladuca) [reply eng/WpfArcadeSdk/tools/InjectModuleInitializer/AddModuleConstructorTask.cs]: That's not correct, there are multiple multi-line patterns in the checks, all of which use SingleLine.

SingleLine means it match across newline characters, see: https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions?view=netframework-4.8

It's counter-intuitive (at least to me).
